{% set name = "mo-kwargs" %}
{% set version = "7.252.22317" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz
  sha256: ff5ba7ae53700e1aa2562836ce0a16a52d0af0e554e8c9fb713141c7f7ae6f55

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - mo-dots ==9.251.22317
    - mo-future ==6.230.22310

test:
  imports:
    - mo_kwargs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klahnakoski/mo-kwargs
  summary: More KWARGS! Let call parameters override kwargs
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
