{% set name = "mo-kwargs" %}
{% set version = "7.148.22086" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz
  sha256: 671372dd4365303bc3b6863619fd6de3944560e3a2e356eacd37ce5c9f0b4e6a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - mo-dots ==9.147.22086
    - mo-future ==6.2.21303

test:
  imports:
    - mo_kwargs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klahnakoski/mo-kwargs
  summary: More KWARGS! Let call parameters override kwargs
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
