{% set name = "mo-kwargs" %}
{% set version = "4.22.21108" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz
  sha256: 9c9d00ab86f1f75013193807d90cad17cbc515384cf3b17b8aff3104a300f7ce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - mo-dots >=3.93.20259
    - mo-future >=3.89.20246

test:
  imports:
    - mo_kwargs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klahnakoski/mo-kwargs
  summary: More KWARGS! Let call parameters override kwargs
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
